font_family JetBrainsMono Nerd Font 

cursor_shape block
cursor_blink_interval 0

shell_integration no-cursor
confirm_os_window_close 0

font_size 11.8

adjust_line_height 100%
window_margin_width 5 3 0 3
placement_strategy top
# background #1E1E2E
background_opacity 0.98

include themes/noctalia.conf
cursor none
cursor_shape block
cursor_blink_interval 0
