layout {
    focus-ring {
        active-color   "{{ colors.primary.default.hex }}"
        inactive-color "{{ colors.surface.default.hex }}"
        urgent-color   "{{ colors.error.default.hex }}"
    }

    border {
        active-color   "{{ colors.primary.default.hex }}"
        inactive-color "{{ colors.surface.default.hex }}"
        urgent-color   "{{ colors.error.default.hex }}"
    }

    tab-indicator {
        active-color   "{{ colors.primary.default.hex }}"
        inactive-color "{{ colors.primary_container.default.hex }}"
        urgent-color   "{{ colors.error.default.hex }}"
    }

    insert-hint {
        color "{{ colors.primary.default.hex }}80"
    }
}

recent-windows {
    highlight {
        active-color "{{ colors.primary.default.hex }}"
        urgent-color "{{ colors.error.default.hex }}"
    }
}

window-rule {
    shadow {
        on
        softness 10
        spread 2
        offset x=0 y=0
        draw-behind-window false
        color "{{ colors.primary.default.hex }}10"
        inactive-color "{{ colors.surface.default.hex }}60"
    }
}
