-- Generated by Noctalia. Do not edit manually.
-- Source template: ~/.config/noctalia/templates/nvim-noctalia.lua
-- Structure mirrors lua/themes/kanagawa-paper.lua (base46 + "kanagawa" overrides).
local M = {}

M.base_30 = {
  white = "{{ colors.on_surface.default.hex }}",
  darker_black = "{{ colors.surface_dim.default.hex }}",
  black = "{{ colors.surface.default.hex }}",
  black2 = "{{ colors.surface_container_low.default.hex }}",
  one_bg = "{{ colors.surface_container.default.hex }}",
  one_bg2 = "{{ colors.surface_container_high.default.hex }}",
  one_bg3 = "{{ colors.surface_container_highest.default.hex }}",
  grey = "{{ colors.outline.default.hex }}",
  grey_fg = "{{ colors.on_surface_variant.default.hex | set_lightness 40 | desaturate 15 }}",
  grey_fg2 = "{{ colors.on_surface_variant.default.hex | set_lightness 45 | desaturate 15 }}",
  light_grey = "{{ colors.on_surface_variant.default.hex | set_lightness 50 | desaturate 15 }}",

  red = "{{ colors.terminal_normal_red.default.hex }}",
  baby_pink = "{{ colors.terminal_bright_red.default.hex }}",
  pink = "{{ colors.terminal_normal_magenta.default.hex }}",

  line = "{{ colors.outline.default.hex }}",

  green = "{{ colors.terminal_normal_green.default.hex }}",
  vibrant_green = "{{ colors.terminal_bright_green.default.hex }}",

  nord_blue = "{{ colors.terminal_bright_blue.default.hex }}",
  blue = "{{ colors.terminal_normal_blue.default.hex }}",

  yellow = "{{ colors.terminal_normal_yellow.default.hex }}",
  sun = "{{ colors.terminal_bright_yellow.default.hex }}",

  purple = "{{ colors.terminal_bright_magenta.default.hex }}",
  dark_purple = "{{ colors.terminal_bright_magenta.default.hex | darken 12 }}",

  teal = "{{ colors.terminal_bright_cyan.default.hex }}",
  orange = "{{ colors.primary.default.hex }}",

  cyan = "{{ colors.terminal_normal_cyan.default.hex }}",
  statusline_bg = "{{ colors.surface.default.hex }}",
  lightbg = "{{ colors.surface_variant.default.hex }}",

  pmenu_bg = "{{ colors.primary.default.hex }}",
  folder_bg = "{{ colors.secondary.default.hex }}",
}

M.base_16 = {
  base00 = "{{ colors.surface.default.hex }}",
  base01 = "{{ colors.surface_container_low.default.hex }}",
  base02 = "{{ colors.surface_container_high.default.hex }}",
  base03 = "{{ colors.on_surface_variant.default.hex | set_lightness 40 | desaturate 15 }}",
  base04 = "{{ colors.on_surface_variant.default.hex }}",
  base05 = "{{ colors.on_surface.default.hex }}",
  base06 = "{{ colors.terminal_foreground.default.hex }}",
  base07 = "{{ colors.terminal_bright_white.default.hex }}",

  base08 = "{{ colors.terminal_normal_red.default.hex }}", -- red
  base09 = "{{ colors.primary.default.hex }}", -- orange / constants
  base0A = "{{ colors.terminal_normal_yellow.default.hex }}", -- yellow
  base0B = "{{ colors.terminal_normal_green.default.hex }}", -- green
  base0C = "{{ colors.terminal_normal_cyan.default.hex }}", -- cyan
  base0D = "{{ colors.terminal_normal_blue.default.hex }}", -- blue
  base0E = "{{ colors.terminal_bright_magenta.default.hex }}", -- purple
  base0F = "{{ colors.terminal_normal_magenta.default.hex }}", -- pink
}

M.polish_hl = {
  treesitter = {
    ["@keyword.import"] = { fg = M.base_30.purple },
    ["@uri"] = { fg = M.base_30.blue },
    ["@tag.delimiter"] = { fg = M.base_30.red },
    ["@variable.member.key"] = { fg = M.base_30.white },
    ["@punctuation.bracket"] = { fg = M.base_30.pmenu_bg },
    ["@punctuation.delimiter"] = { fg = M.base_30.white },
  },

  syntax = {
    Number = { fg = M.base_30.baby_pink },
  },
}

M.type = "dark"

M = require("base46").override_theme(M, "kanagawa")

return M
