-- Default fallback palette (tracked in git).
-- Generated hypr/noctalia.lua is git-ignored; to refresh: render theme, then copy it over this file.
-- Generated by Noctalia

local primary = "rgb(a9b665)"
local surface = "rgb(32302f)"
local on_surface = "rgb(ddc7a1)"
local secondary = "rgb(e78a4e)"
local on_secondary = "rgb(32302f)"
local error = "rgb(ea6962)"
local on_error = "rgb(32302f)"

local function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = primary,
                inactive_border = surface,
            },
        },
        group = {
            col = {
                border_active = secondary,
                border_inactive = surface,
                border_locked_active = error,
                border_locked_inactive = surface,
            },

            groupbar = {
                col = {
                    active = secondary,
                    inactive = surface,
                    locked_active = error,
                    locked_inactive = surface,
                },
                text_color = on_secondary,
                text_color_inactive = on_surface,
                text_color_locked_active = on_error,
                text_color_locked_inactive = on_surface,
            },
        },
    })
end

return {
    colors = {
        primary = primary,
        surface = surface,
        on_surface = on_surface,
        secondary = secondary,
        on_secondary = on_secondary,
        error = error,
        on_error = on_error,
    },
    apply_theme = apply_theme
}
