# современное поведение
keep-open=yes
force-window=yes
cursor-autohide=250
save-position-on-quit=yes
# рисовать контекстное меню силами mpv, а не нативное ОС (по доке ModernZ)
load-context-menu=yes

# нормальное качество UI поведения
osc=no
osd-bar=no
border=no
vo=gpu-next
gpu-context=waylandvk
hwdec=auto-safe
hwdec-codecs=all
video-sync=display-resample
video-sync-max-factor=5
# сгладить чтение с медленного USB-HDD (NTFS)
cache=yes
demuxer-max-bytes=256MiB
demuxer-max-back-bytes=64MiB
demuxer-donate-buffer=yes
# sub-fonts-dir=/usr/share/mpv/fonts
# fonts-dir=/usr/share/mpv/fonts
