##############################################
#                                            #
#          Superfile — Noctalia Theme        #
#                                            #
##############################################

# Code Syntax Highlighting
code_syntax_highlight = "catppuccin-mocha"

# Full Screen
full_screen_fg = "#d9d1ba"
full_screen_bg = "#1a2026"

# Gradient
gradient_color = [
  "#d9a78b",
  "#d96c6c"
]

# File Panel
file_panel_fg = "#d9d1ba"
file_panel_bg = "#1a2026"
file_panel_border = "#5e6b77"
file_panel_border_active = "#d9a78b"
file_panel_top_directory_icon = "#d9a78b"
file_panel_top_path = "#7794a6"
file_panel_item_selected_fg = "#d9a78b"
file_panel_item_selected_bg = "#20272e"

# Footer
footer_fg = "#d9d1ba"
footer_bg = "#1a2026"
footer_border = "#5e6b77"
footer_border_active = "#d9a78b"

# Sidebar
sidebar_fg = "#d9d1ba"
sidebar_bg = "#1a2026"
sidebar_title = "#8ba37a"
sidebar_border = "#20272e"
sidebar_border_active = "#d9a78b"
sidebar_item_selected_fg = "#d9a78b"
sidebar_item_selected_bg = "#20272e"
sidebar_divider = "#5e6b77"

# Modals
modal_fg = "#d9d1ba"
modal_bg = "#1a2026"
modal_border_active = "#d9a78b"
modal_cancel_fg = "#d9d1ba"
modal_cancel_bg = "#5e6b77"
modal_confirm_fg = "#d9d1ba"
modal_confirm_bg = "#243947"

# Help Menu
help_menu_hotkey = "#d9a78b"
help_menu_title = "#8ba37a"

# Special
cursor = "#d9d1ba"
correct = "#d9a78b"
error = "#d96c6c"
hint = "#7794a6"
cancel = "#5e6b77"
