##############################################
#                                            #
#          Superfile — Noctalia Theme        #
#                                            #
##############################################

# Code Syntax Highlighting
code_syntax_highlight = "catppuccin-mocha"

# Full Screen
full_screen_fg = "#dcd7ba"
full_screen_bg = "#1f1f28"

# Gradient
gradient_color = [
  "#c4b28a",
  "#c4746e"
]

# File Panel
file_panel_fg = "#dcd7ba"
file_panel_bg = "#1f1f28"
file_panel_border = "#566d79"
file_panel_border_active = "#c4b28a"
file_panel_top_directory_icon = "#c4b28a"
file_panel_top_path = "#8ea49e"
file_panel_item_selected_fg = "#c4b28a"
file_panel_item_selected_bg = "#2a2a37"

# Footer
footer_fg = "#dcd7ba"
footer_bg = "#1f1f28"
footer_border = "#566d79"
footer_border_active = "#c4b28a"

# Sidebar
sidebar_fg = "#dcd7ba"
sidebar_bg = "#1f1f28"
sidebar_title = "#938aa9"
sidebar_border = "#2a2a37"
sidebar_border_active = "#c4b28a"
sidebar_item_selected_fg = "#c4b28a"
sidebar_item_selected_bg = "#2a2a37"
sidebar_divider = "#566d79"

# Modals
modal_fg = "#dcd7ba"
modal_bg = "#1f1f28"
modal_border_active = "#c4b28a"
modal_cancel_fg = "#dcd7ba"
modal_cancel_bg = "#566d79"
modal_confirm_fg = "#dcd7ba"
modal_confirm_bg = "#304f47"

# Help Menu
help_menu_hotkey = "#c4b28a"
help_menu_title = "#938aa9"

# Special
cursor = "#c4b28a"
correct = "#c4b28a"
error = "#c4746e"
hint = "#8ea49e"
cancel = "#566d79"
