unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"
# run-shell "~/.config/scripts/link_powerkit_themes.sh"

set -g status-position top
set -g default-terminal "tmux-256color"
bind-key C-q kill-session
bind-key C-o display-popup -E "bash -lc ~/.config/scripts/resurrect_fzf.sh"
bind-key S display-popup -E -w 40% -h 3 -x C -y C "bash -lc ~/.config/scripts/resurrect_save.sh"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r C-h resize-pane -L 
bind-key -r C-j resize-pane -D 
bind-key -r C-k resize-pane -U 
bind-key -r C-l resize-pane -R 
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

#Options
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

#Keybinding and other things
set -g prefix C-f
set -g mouse on
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy on     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi

# Basic configuration
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

#List of additional plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

#Plugins Settings
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'green'
set -g @floax-text-color 'white'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'
set -g @sessionx-bind-zo-new-window 'ctrl-y'
set -g @sessionx-auto-accept 'off'
set -g @sessionx-bind 'o'
set -g @sessionx-x-path '~/dotfiles'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-custom-paths-subdirectories 'false'
set -g @sessionx-filter-current 'false'
set -g @continuum-save-interval 15
set -g @continuum-save-on-quit 'off'
set -g @continuum-restore 'off'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'on'

source-file -q "$HOME/.config/tmux/status-line.conf"

run '~/.tmux/plugins/tpm/tpm'
source-file -q "$HOME/.config/tmux/themes/noctalia-palette.conf"
